# action.yml
name: 'Testim CLI'
description: 'Run tests on Testim.io'
inputs:
  token:  # id of input
    description: 'Testim auth token'
    required: true
  project:
    description: 'Project ID'
    required: true
  grid:
    description: 'Grid to run the tests on'
    required: true
    default: "Testim-Grid"
  suite:
    description: 'The test suite to run'
    required: true
  test-config:
    description: 'The test configuration'
    required: false
    default: MacOS-Chrome
  retries:
    description: 'The number of retries'
    required: false
    default: '1'
  base-url:
    description: 'The base url to test at'
    required: false
    default: https://staging-apply.verteva.com.au
  parallel:
    description: 'Number of parallel runs'
    required: false
    default: 4
  
  
  

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.project }}
    - ${{ inputs.grid }}
    - ${{ inputs.suite }}
    - ${{ inputs.test-config }}
    - ${{ inputs.retries }}
    - ${{ inputs.base-url }}
    - ${{ inputs.parallel }}
